/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kbmgozxdvayucyjohuhl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtibWdvenhkdmF5dWN5am9odWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTQyMDMsImV4cCI6MjA3MDgzMDIwM30.11UCcaAr-7dDpHhdI7-LHCwYhipnMqREwc0gTfisefA"